services:
  springboot-app:
    image: notes_backend
    restart: always
    build: ./docker/backend/
    volumes:
      - ./docker/backend/firebase_service_account_key.json:/firebase_service_account_key.json
    container_name: notes_backend_container
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: notes_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
  database:
    container_name: notes_postgres
    image: postgres
    volumes:
          - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8912:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes


